### ISSUE TITLE
Error on installing passionfruite

### ISSUE THREAD

**Issue by illnino** [chaitin/passionfruit#18]
## ENV

node - 8.9.4
nvm - 0.31.7
frida - 10.6.55

Mac - 10.13.3

## Error Log

Incompatible with frida 10.6.55?

```
➜  ~ npm install -g passionfruit
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
/Users/its/.nvm/versions/node/v8.9.4/bin/passionfruit -> /Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/bin/cli.js

> fsevents@1.1.3 install /Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/node_modules/fsevents
> node install

[fsevents] Success: "/Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uws@9.14.0 install /Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> frida@10.6.55 install /Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/frida-v10.6.55-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/its/.npm/_prebuilds/https-github.com-frida-frida-releases-download-10.6.55-frida-v10.6.55-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/frida/frida/releases/download/10.6.55/frida-v10.6.55-node-v57-darwin-x64.tar.gz
prebuild-install WARN install connect ETIMEDOUT 52.216.17.112:443
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2018-03-01 14:39:02.391 xcodebuild[55722:7190099] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FortifyScanningPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/frida_binding/src/addon.o
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Users/its/.nvm/versions/node/v8.9.4/bin/node" "/Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/its/.nvm/versions/node/v8.9.4/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@10.6.55 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@10.6.55 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/its/.npm/_logs/2018-03-01T06_39_05_828Z-debug.log
```

**Comment by ChiChou** [comment]
GitHub 上的预编译包被墙了，想办法弄个代理吧

**Comment by illnino** [comment]
Thanks for the tip. I could successfully installed passionfruit now.
