### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by jacinzhang** [chaitin/passionfruit#27]
```
 XIN😄   ~  node --version
v9.11.1
 XIN😄   ~  npm --version
5.6.0
 XIN😄   ~  npm install -g passionfruit
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
/Users/XIN/.nvm/versions/node/v9.11.1/bin/passionfruit -> /Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/passionfruit/bin/cli.js

> fsevents@1.2.0 install /Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/passionfruit/node_modules/fsevents
> node install

[fsevents] Success: "/Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/passionfruit/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> frida@10.7.7 install /Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install connect ETIMEDOUT 192.30.253.113:443
  CXX(target) Release/obj.target/frida_binding/src/addon.o
In file included from ../src/addon.cc:1:
In file included from ../src/application.h:4:
In file included from ../src/glib_object.h:4:
In file included from ../src/runtime.h:4:
../src/glib_context.h:4:10: fatal error: 'frida-core.h' file not found
#include <frida-core.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/frida_binding/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/Users/XIN/.nvm/versions/node/v9.11.1/bin/node" "/Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/XIN/.nvm/versions/node/v9.11.1/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@10.7.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@10.7.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XIN/.npm/_logs/2018-04-23T07_53_10_561Z-debug.log
```

**Comment by ChiChou** [comment]
https://github.com/chaitin/passionfruit#have-problem-with-npm-install
https://github.com/chaitin/passionfruit/wiki/%E4%BD%BF%E7%94%A8%E5%9B%BD%E5%86%85%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F%E5%AE%89%E8%A3%85

**Comment by jacinzhang** [comment]
perfect,thansk
