### ISSUE TITLE
unable to launch Passionfruit

### ISSUE THREAD

**Issue by kryptoknight13** [chaitin/passionfruit#30]
getting below error: 

AMAC02RN1S9G8WP:~ akanksha.bana$ passionfruit 
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'big-integer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/passionfruit/node_modules/frida/lib/ptr.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
AMAC02RN1S9G8WP:~ akanksha.bana$

**Comment by ChiChou** [comment]
The problem is your node.js runtime. Try reinstall node.js and reinstall `npm install -g passionfruit`
