### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by DSKcpp** [chaitin/passionfruit#35]
run passionfruit

```
/usr/local/lib/node_modules/passionfruit/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/compiled/8.11.3/darwin/x64/frida_binding.node
 → /Volumes/ssd/hook/Weibo/frida_binding.node
    at bindings (/usr/local/lib/node_modules/passionfruit/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/passionfruit/node_modules/frida/dist/index.js:16:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/passionfruit/app.js:7:15)
```

passionfruit@0.4.3
node v8.11.3
npm 5.6.0

**Comment by ChiChou** [comment]
Node.js native binding is broken. You need to reinstall the package.

#19 

https://github.com/chaitin/passionfruit/wiki/%E4%BD%BF%E7%94%A8%E5%9B%BD%E5%86%85%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F%E5%AE%89%E8%A3%85
