### ISSUE TITLE
Error While running Passion fruit:

### ISSUE THREAD

**Issue by Soujanya2107** [chaitin/passionfruit#43]
listening on http://localhost:31337
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:31337
    at Server.setupListenHandle [as _listen2] (net.js:1334:14)
    at listenInCluster (net.js:1382:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1508:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1361:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(virtual-python3) AMAC02TM00TGG7J:bin soujanya.mohanhegde$ killall -9 node
[1]+  Killed: 9               passionfruit
(virtual-python3) AMAC02TM00TGG7J:bin soujanya.mohanhegde$ passionfruit
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 16ms 208b

  InternalServerError: ENOENT: no such file or directory, stat '/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/gui/static/build.js'
      at Object.throw (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/app.js:74:21)

  <-- GET /favicon.ico
  --> GET /favicon.ico 200 0ms 208b
  <-- GET /
  --> GET / 200 0ms 208b

  InternalServerError: ENOENT: no such file or directory, stat '/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/gui/static/build.js'
      at Object.throw (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/app.js:74:21)

  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 208b

**Comment by Soujanya2107** [comment]
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 100ms 208b

  InternalServerError: ENOENT: no such file or directory, stat '/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/gui/static/build.js'
      at Object.throw (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/app.js:74:21)

  <-- GET /favicon.ico
  --> GET /favicon.ico 200 0ms 208b
  <-- GET /
  --> GET / 200 1ms 208b

  InternalServerError: ENOENT: no such file or directory, stat '/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/gui/static/build.js'
      at Object.throw (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/Users/soujanya.mohanhegde/virtual-python3/bin/passionfruit/app.js:74:21)

**Comment by ChiChou** [comment]
It's a nodejs project and totally not involving python.

Have you tried `npm uninstall -g passionfruit; npm install -g passionfruit`?

**Comment by Soujanya2107** [comment]
Yes I tried it
 This error:
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 19ms 208b

  InternalServerError: ENOENT: no such file or directory, stat '/Users/soujanya.mohanhegde/passionfruit/gui/static/build.js'
      at Object.throw (/Users/soujanya.mohanhegde/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/Users/soujanya.mohanhegde/passionfruit/app.js:74:21)

**Comment by Soujanya2107** [comment]
it display listening on http://localhost:31337, but after connecting the device and while browsing the same port : blank page appears

**Comment by ChiChou** [comment]
@Soujanya2107 

Please, use the command: `npm uninstall -g passionfruit; npm install -g passionfruit; passionfruit`
You don't have to clone the repo

**Comment by ChiChou** [comment]
If you are cloning the repo you need to `npm run dev` instead, and it's certainly not what you want
https://github.com/chaitin/passionfruit#development-setup
Please read the document.
