### ISSUE TITLE
 error frida@12.3.2 install: `prebuild-install || node-gyp rebuild`

### ISSUE THREAD

**Issue by DSTDevOPs** [chaitin/passionfruit#45]
Hi. I tried to install passionfruit on my mac. But got the following error:

```
18015 silly install frida@12.3.2
18016 info lifecycle frida@12.3.2~install: frida@12.3.2
18017 verbose lifecycle frida@12.3.2~install: unsafe-perm in lifecycle true
18018 verbose lifecycle frida@12.3.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/passionfruit/node_modules/frida/node_modules/.bin:/usr/local/lib/node_modules/passionfruit/node_modules/.bin:/usr/local/lib/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/Users/shilpa.ranganatha/.rvm/gems/ruby-2.4.0/bin:/Users/shilpa.ranganatha/.rvm/gems/ruby-2.4.0@global/bin:/Users/shilpa.ranganatha/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/shilpa.ranganatha/.rvm/bin:/Applications/010 Editor.app/Contents/CmdLine
18019 verbose lifecycle frida@12.3.2~install: CWD: /usr/local/lib/node_modules/passionfruit/node_modules/frida
18020 silly lifecycle frida@12.3.2~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
18021 silly lifecycle frida@12.3.2~install: Returned: code: 1  signal: null
18022 info lifecycle frida@12.3.2~install: Failed to exec install script
18023 timing action:install Completed in 3705ms
18024 verbose unlock done using /Users/shilpa.ranganatha/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
18025 timing stage:rollbackFailedOptional Completed in 1617ms
18026 timing stage:runTopLevelLifecycles Completed in 35423ms
18027 verbose stack Error: frida@12.3.2 install: `prebuild-install || node-gyp rebuild`
18027 verbose stack Exit status 1
18027 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18027 verbose stack     at EventEmitter.emit (events.js:159:13)
18027 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18027 verbose stack     at ChildProcess.emit (events.js:159:13)
18027 verbose stack     at maybeClose (internal/child_process.js:943:16)
18027 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
18028 verbose pkgid frida@12.3.2
18029 verbose cwd /Users/shilpa.ranganatha
18030 verbose Darwin 17.7.0
18031 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "install" "-g" "passionfruit"
18032 verbose node v9.3.0
18033 verbose npm  v6.8.0
18034 error code ELIFECYCLE
18035 error errno 1
18036 error frida@12.3.2 install: `prebuild-install || node-gyp rebuild`
18036 error Exit status 1
18037 error Failed at the frida@12.3.2 install script.
18037 error This is probably not a problem with npm. There is likely additional logging output above.
18038 verbose exit [ 1, true ]
```

Python version - 3.6.4
node-gyp version - 3.6.2

Please help me resolve the above issue.

**Comment by ChiChou** [comment]
Is there any additional log?

**Comment by pharazone** [comment]
I have the same problem……这个问题我今天也碰到了，在编译绑定的frida  version 12.3.3的时候

**Comment by ChiChou** [comment]
Seems like `frida` module doesn't provide prebuilt packages yet and build from source failed.
@pharazone @DSTDevOPs you can have a temporary workaround by downgrade to node@10:

```shell
brew remove node
brew install node@10
```
