### ISSUE TITLE
npm start giving error.

### ISSUE THREAD

**Issue by pragyan1994** [chaitin/passionfruit#6]
The following is the error i am getting when i am executing "npm start, even after the "npm run build " is all working fine.

node_modules$: npm start

> Passionfruit@0.0.2 start /Users/pragyan.a.paramita/passionfruit
> cross-env NODE_ENV=production node .

/Users/pragyan.a.paramita/passionfruit/app.js:31
  .get('/devices', async (ctx) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Passionfruit@0.0.2 start: `cross-env NODE_ENV=production node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Passionfruit@0.0.2 start script 'cross-env NODE_ENV=production node .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Passionfruit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Passionfruit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Passionfruit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pragyan.a.paramita/passionfruit/node_modules/npm-debug.log

**Comment by ChiChou** [comment]
Node v6.11.5 is too old for the project, consider upgrading to latest (8.8.1 now)

**Comment by pragyan1994** [comment]
Did you notice the syntax error the tool is throwing ??

/Users/pragyan.a.paramita/passionfruit/app.js:31
.get('/devices', async (ctx) => {
^

SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:383:7)
at startup (bootstrap_node.js:149:9)

**Comment by pragyan1994** [comment]
Also, i updated node to latest, now my build is failing.


ERROR in ./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-bf5e4d38","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: Error: Missing binding /Users/pragyan.a.paramita/passionfruit/gui/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/pragyan.a.paramita/passionfruit/gui/node_modules/webpack/lib/NormalModule.js:268:15)
 @ ./~/vue-style-loader!./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-bf5e4d38","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-326
 @ ./src/App.vue
 @ ./src/main.js

**Comment by ChiChou** [comment]
There's nothing wrong with the syntax. It is your node version does not support `await/async` keyword

**Comment by ChiChou** [comment]
And after you upgrade the node engine, you have to remove `rm -rf node_modules`, then run the following command once again.

```
npm install
npm run build
``

**Comment by pragyan1994** [comment]
hey,

thank you so much for helping out! works great :)

**Comment by pragyan1994** [comment]
on starting the server it is giving me a "Internal server error"

attaching a screen shot. 
<img width="1351" alt="screen shot 2017-10-26 at 5 21 52 pm" src="https://user-images.githubusercontent.com/17158890/32051437-39acea50-ba72-11e7-91ac-4f2e6e098500.png">

**Comment by ChiChou** [comment]
Any logs from terminal?

**Comment by pragyan1994** [comment]
PORT=9090 npm start

> Passionfruit@0.0.2 start /Users/pragyan.a.paramita/passionfruit
> cross-env NODE_ENV=production node .

listening on http://localhost:9090
  <-- GET /
  --> GET / 200 8ms 206b
  <-- GET /dist/build.js
  --> GET /dist/build.js 200 5ms 782.04kb
  <-- GET /dist/0.build.js
  --> GET /dist/0.build.js 200 1ms 41.6kb
  <-- GET /dist/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
  --> GET /dist/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 1ms 43.26kb
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 0ms 206b
  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 206b

  InternalServerError: Unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
      at Object.throw (/Users/pragyan.a.paramita/passionfruit/node_modules/koa/lib/context.js:91:11)
      at app.use.use.use (/Users/pragyan.a.paramita/passionfruit/app.js:84:18)
      at <anonymous>

  <-- GET /favicon.ico
  --> GET /favicon.ico 200 1ms 206b

The log over the terminal, i assume it to be frida error! Any idea how to resolve this ?

**Comment by ChiChou** [comment]
Upgrade frida framework in Cydia

**Comment by pragyan1994** [comment]
Its done, it is working fine now!
Thanks @ChiChou  :)
