### ISSUE TITLE
Unable to install via npm on OS X

### ISSUE THREAD

**Issue by thistehneisen** [chaitin/passionfruit#62]
Tried also with sudo

```
╭─nils@nilsdigital ~
╰─$ npm install -g passionfruit                                                                                                                    1 ↵
/usr/local/bin/passionfruit -> /usr/local/lib/node_modules/passionfruit/bin/cli.js

> frida@12.7.16 install /usr/local/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.9.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/passionfruit/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.7.16 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.7.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nils/.npm/_logs/2019-11-05T17_27_32_959Z-debug.log
```

**Comment by ChiChou** [comment]
`No prebuilt binaries found` 

Please use node.js LTS (Long Tem Support)
