### ISSUE TITLE
InternalServerError when selecting iOS Device

### ISSUE THREAD

**Issue by schniggie** [chaitin/passionfruit#64]
```
node --version
v10.17.0
#
npm --version
6.13.2
#
frida --version
12.7.24
#
uname -a 
Linux kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux
#
npm install -g passionfruit
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/bin/passionfruit -> /usr/lib/node_modules/passionfruit/bin/cli.js

> passionfruit@0.5.5 postinstall /usr/lib/node_modules/passionfruit
> node scripts/post-install.js

successfully created database
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/passionfruit/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ passionfruit@0.5.5
```

Running current passionfruit on latest Kali 2019.3 fails for me when selecting "iOS Device" from the webinterface. Following error appears:

```
passionfruit               
listening on http://localhost:31337
  <-- GET /
  --> GET / 200 4ms 338b
  <-- GET /static/build.js
  --> GET /static/build.js 200 4ms 865.29kb
  <-- GET /static/0.build.js
  --> GET /static/0.build.js 200 2ms 55.2kb
  <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
  --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 1ms 16.33kb

  InternalServerError: Unexpected result while trying to read pair record: 2
      at Object.throw (/usr/lib/node_modules/passionfruit/node_modules/koa/lib/context.js:97:11)
      at app.use.use.use (/usr/lib/node_modules/passionfruit/app.js:74:21)
```

Tested with 2 different iDevices 12.1.3 and 13.2.3, but same result.

**Comment by ChiChou** [comment]
Seems like your device is not well paired.
Try `idevicepair pair` and see what happens

This command is part of `libimobiledevice-utils`

**Comment by schniggie** [comment]
```
idevicepair pair
*** stack smashing detected ***: <unknown> terminated
[1]    81514 abort      idevicepair pair
```

That doesn't look good. Will try some debugging and update you.

**Comment by ChiChou** [comment]
Did you solve it?

**Comment by schniggie** [comment]
Yes, rebuilt `libimobiledevice-utils` from source. But don't know what happened with my kali package.
