### ISSUE TITLE
Can't install passionfruit on the newest node 14.0.0

### ISSUE THREAD

**Issue by r3ggi** [chaitin/passionfruit#73]
Hey,

I upgraded node on my macOS to 14.0.0 and observed that passionfruit is unable to install with `npm install -g passionfruit`

Error log below:

```sh
$ npm install -g passionfruit
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/testuser/.npm-global/bin/passionfruit -> /Users/testuser/.npm-global/lib/node_modules/passionfruit/bin/cli.js

> frida@12.8.20 install /Users/testuser/.npm-global/lib/node_modules/passionfruit/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.0.0 runtime=node arch=x64 libc= platform=darwin)
gyp: binding.gyp not found (cwd: /Users/testuser/.npm-global/lib/node_modules/passionfruit/node_modules/frida) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node/14.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/testuser/.npm-global/lib/node_modules/passionfruit/node_modules/frida
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@12.8.20 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frida@12.8.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/testuser/.npm/_logs/2020-04-24T09_37_44_401Z-debug.log
```

**Comment by ChiChou** [comment]
> No prebuilt binaries found

`frida` is a native nodejs module, thus you need to either compile it yourself or use the official prebuilt paclage. Downgrade to nodejs LTS (currently 12) to get prebuilt work
