### ISSUE TITLE
Error when trying to install passionfruit

### ISSUE THREAD

**Issue by B4RD4k** [chaitin/passionfruit#76]
I'm getting this error when trying to install passionfruit on a Kali machine for instance.
Does anybody overcome this?

Thanks

root@kali:~# passionfruit 
/usr/local/lib/node_modules/passionfruit/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/out/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/Debug/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/out/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/Release/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/build/default/frida_binding.node
 → /usr/local/lib/node_modules/passionfruit/node_modules/frida/compiled/10.21.0/linux/x64/frida_binding.node
 → /root/frida_binding.node
    at bindings (/usr/local/lib/node_modules/passionfruit/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/passionfruit/node_modules/frida/dist/native.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/passionfruit/node_modules/frida/dist/cancellable.js:4:18)

**Comment by ChiChou** [comment]
1. make sure you are on node.js 12.x
2. retry `npm install -g passionfruit`
